### ISSUE TITLE
Enhancement: SVG Support

### ISSUE THREAD

**Issue by dimalebid** [Muetze42/nova-menu#10]
Hello, can I have detailed instructions on how to do this?

**Comment by Muetze42** [comment]
Yes, you have to insert it manually if you want to. 

The problem is always, if every package brings the font with it, it is included several times at the end.

**Comment by dimalebid** [comment]
а можете добавить метод ->svgIcon?

вт, 28 мар. 2023 г. в 12:53, Norman Huth ***@***.***>:

**Comment by dimalebid** [comment]
я туда просто буду запихивать svg и не нужно никаких шрифтов подключать

вт, 28 мар. 2023 г. в 12:57, Дима Лебедь ***@***.***>:

**Comment by Muetze42** [comment]
Please in englich.

Yes. I can implement the week.

**Comment by dimalebid** [comment]
You can add the ->svgIcon(string $svg) method. There we will cram svg ?

вт, 28 мар. 2023 г. в 13:14, Norman Huth ***@***.***>:

**Comment by Muetze42** [comment]
Current status:  
The plugin is in complete refactor and tonight (CET) or tomorrow will come the update with the possibility to use SVG icons & files.

**Comment by dimalebid** [comment]
Hello, very good, thanks!

пт, 31 мар. 2023 г. в 14:09, Norman Huth ***@***.***>:

**Comment by Muetze42** [comment]
I have just created a new release.

> - Refactor complete package
> - Add `svgIcon()` method
> - Add `imageIcon()` method
> - Add `htmlIcon()` method
> - Add `iconHeight()` method

**Comment by Muetze42** [comment]
I have just created a new release.

> - Refactor complete package
> - Add `svgIcon()` method
> - Add `imageIcon()` method
> - Add `htmlIcon()` method
> - Add `iconHeight()` method

**Comment by Muetze42** [comment]
Today Release

> - Add gap option for label icons
> - Add Font Awesome install command
> - Add Tailwind CSS colors command
> - Add methods to add classes on element, icon and label

**Comment by dimalebid** [comment]
Hello, very good, thanks!

сб, 1 апр. 2023 г. в 11:55, Norman Huth ***@***.***>:
