### ISSUE TITLE
Highlighting lost after last update

### ISSUE THREAD

**Issue by dm-pf** [Muetze42/nova-menu#19]
Hi, thanks for this wonderful package!

You probably did a "Find & Replace" which is a handy but scary functionality in your IDE.

https://github.com/Muetze42/nova-menu/blob/7359d48c30051e59e6ab59b9321f4fc01aea79a9/resources/js/components/MenuItem.vue#L7

That isn't how [class binding](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes) works. You might want to do something like this instead?

```javascript
:class="{ 'inertia-link-active': item.active, item.icons.classes.elem: true }" 
```

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-menu/releases/tag/1.3.3
