### ISSUE TITLE
Menu Filter

### ISSUE THREAD

**Issue by Keko-94** [Muetze42/nova-menu#41]
MainMenu.vue Line 30:
        <div className="menu-filter menu-filter-bottom" v-if="$page.props.menuAdvPosition && ['top', 'both'].includes($page.props.menuAdvPosition)">

should be ['bottom', 'both'] instead of top

MenuFilter::activate('both')->placeholder(__('Search menu')) broke all my translations, I don't know why :/

**Comment by Muetze42** [comment]
So for me, the search runs as intended, even in Switzerland.

The data comes from the database and there is therefore a debounce of 300ms so that the server is not flooded.
 Is possibly that meant?

**Comment by Muetze42** [comment]
Menu Filter Bottom was wrong. Is fixed in the current release.

Have You tested it without translation? 
`placeholder('Search menu')`

**Comment by Keko-94** [comment]
Thanks for the fix.
Without translation it's working.

**Comment by Muetze42** [comment]
Curious. So I use the package in several projects without problems. I can still try around a bit to see if I can recreate the error.
