### ISSUE TITLE
Visual error on Nova v4.27.14

### ISSUE THREAD

**Issue by henryavila** [Muetze42/nova-menu#43]
Laravel nova 4.27.14 introduced [Improved the visual style of menus](https://nova.laravel.com/releases/4.27.14) 
This maked the visual menu break

In v4.27.13

![image](https://github.com/Muetze42/nova-menu/assets/8429941/7312680b-d92a-4a1b-b693-9327b2987b2a)

in v4.27.14

![image](https://github.com/Muetze42/nova-menu/assets/8429941/529838eb-6455-463b-a54b-902940477d53)

**Comment by Muetze42** [comment]
Oh. I check it tomorrow

**Comment by Muetze42** [comment]
I create a pre-release.
https://github.com/Muetze42/nova-menu/releases/tag/v1.7.5-rc.1

After further testing, refactor to PSR-12 & ESLint this will also be the next final release if no one or anyone else finds a bug.

**Comment by Muetze42** [comment]
[v1.7.5: Nova 4.27.14 compatibility](https://github.com/Muetze42/nova-menu/releases)

**Comment by Keko-94** [comment]
The search bar doesn't work : it doesn't filter the menu.
Thanks !

**Comment by Muetze42** [comment]
Thank you. Have corrected it.

I'll have to see if and how to write tests in Vue. Would be useful if you have to touch such a package again after months....

**Comment by henryavila** [comment]
Working perfectly @Muetze42.
Thanks for the package and the correction!!!
