### ISSUE TITLE
Menu search lost styles in newest version of Nova

### ISSUE THREAD

**Issue by webard** [Muetze42/nova-menu#49]
Hello,

after upgrading Laravel Nova to newest version, search input of menu looks like this:
<img width="259" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/ef092a5f-8c14-4668-9003-3f347d1b604f">

Error happens only in dark mode, in light mode everything is fine:
<img width="267" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/4ae54e95-ae3f-4279-b881-e0cc40cb942e">

By the way, what do you think about making this field looking more like other search inputs?
<img width="562" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/7a40f59e-30a9-43d8-afac-0c4456a3bd16">

**Comment by Muetze42** [comment]
Thanks for the report.

The classes have been changed. This and the Perspectives Package now use the old and new classes.

https://github.com/Muetze42/nova-menu/releases
