### ISSUE TITLE
Founded resources in menu disappears after switching to specific resource

### ISSUE THREAD

**Issue by webard** [Muetze42/nova-menu#50]
Hello,

when I search text, i can find resource by name:
<img width="288" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/c0dbc2e9-c46f-48b5-b582-e3b37856b2d8">

when I click to Role everything is fine, i still can see found resource. But when I go to specific resource by Eye icon:
<img width="1528" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/dbb35a4d-c7cc-4ff0-a535-4b07b06781fe">

Menu starts to show entire menu, even if text in search box is still present:
<img width="255" alt="image" src="https://github.com/Muetze42/nova-menu/assets/855788/2fb08ed2-d2c6-4ae7-a4b8-e26b7b13afc0">

**Comment by Muetze42** [comment]
Release 1.7.9+

https://github.com/Muetze42/nova-menu/releases
