### ISSUE TITLE
Menu group arrow not rotating

### ISSUE THREAD

**Issue by nikoo-eshratabadi** [Muetze42/nova-menu#53]
Laravel Version: 10.10
Nova Version: 4.25.1
PHP Version: 8.1.23

Hello 
I have a little problem with the MenuGroup. the little arrow > doesn't change when i open it like it does on your live preview. 
![image](https://github.com/Muetze42/nova-menu/assets/170652568/76d97042-9e8b-45c2-a70c-852d000da757)

Everything else works perfectly!
I have a collapsable MenuGroup inside a MenuSection and have imported everything according to your documentation.

big fan by the way!

**Comment by Muetze42** [comment]
I'm on vacation starting next week. I'll be able to work through the tasks on GitHub then

**Comment by nikoo-eshratabadi** [comment]
i did and override on the css and fixed it so don't do it on my account! still a big fan:D

**Comment by Muetze42** [comment]
@nikoo-eshratabadi Can You make a PR with fix for all users?

**Comment by nikoo-eshratabadi** [comment]
I don't know if i can sorry. 
I added this line to one of my css assets to fix it.

 ```  
    .ltr\:-rotate-90:where([dir=ltr],[dir=ltr] *){
        --tw-rotate: -90deg !important;
    }
```
