### ISSUE TITLE
Feature Request: Add icons for group and item

### ISSUE THREAD

**Issue by scramatte** [Muetze42/nova-menu#6]
Hi,

Can you  add feature to add icons for group and item?

Regards

**Comment by Muetze42** [comment]
I will try the week to take care of the matter. Shortly before the end of the year is always a lot to do....

**Comment by scramatte** [comment]
Thank you

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-menu/releases/tag/1.1.0
